CREATE TABLE DEPARTMENT
(
    id   BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

CREATE TABLE EMPLOYEE(
    id BIGINT AUTO_INCREMENT PRIMARY KEY ,
    name VARCHAR(255) NOT NULL,
    department_id BIGINT,
    FOREIGN KEY (department_id) REFERENCES  DEPARTMENT(id)
);


CREATE TABLE EMPLOYEE_SKILLS
(
    employee_id BIGINT,
    skill VARCHAR(255),
    FOREIGN KEY (employee_id) REFERENCES EMPLOYEE(id)

);



